name: Basic CI

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Print message
        run: echo "Running CI pipeline for Day 20!"

      - name: Show directory
        run: ls -la

      - name: Show date
        run: date